CREATE TABLE IF NOT EXISTS commercial_request_installation_facts (
  request_id TEXT PRIMARY KEY NOT NULL,
  version INTEGER NOT NULL,
  site_name TEXT,
  street TEXT NOT NULL,
  city TEXT NOT NULL,
  county TEXT,
  postal_code TEXT,
  country_code TEXT NOT NULL,
  contact_name TEXT,
  contact_phone TEXT,
  access_notes TEXT,
  measurement_status TEXT NOT NULL,
  mounting_surface_width_mm INTEGER,
  mounting_surface_height_mm INTEGER,
  installation_elevation_mm INTEGER,
  measured_at TEXT,
  measurement_notes TEXT,
  facade_type TEXT NOT NULL,
  facade_other_note TEXT,
  fixing_method TEXT NOT NULL,
  fixing_other_note TEXT,
  site_electrical TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (request_id) REFERENCES commercial_requests(request_id)
);
