export {
  CUSTOMER_ADDRESS_MAX_LENGTH,
  CUSTOMER_CITY_MAX_LENGTH,
  CUSTOMER_CONTACT_NAME_MAX_LENGTH,
  CUSTOMER_CUI_MAX_LENGTH,
  CUSTOMER_DISPLAY_NAME_MAX_LENGTH,
  CUSTOMER_EMAIL_MAX_LENGTH,
  CUSTOMER_MUTATION_ERRORS,
  CUSTOMER_NOTES_MAX_LENGTH,
  CUSTOMER_PHONE_MAX_LENGTH,
  CUSTOMER_STATUSES,
  activeCustomers,
  copyFrozenCustomerIdentity,
  createCustomer,
  customerFromRow,
  customerStatusLabel,
  emptyCustomerProfile,
  findCustomer,
  freezeCustomerIdentity,
  generateCustomerId,
  isCustomerStatus,
  renameCustomer,
  retireCustomer,
  updateCustomer,
  type Customer,
  type CustomerMutationError,
  type CustomerMutationResult,
  type CustomerProfile,
  type CustomerProfilePatch,
  type CustomerStatus,
  type FrozenCustomerIdentity,
} from "./identity.js";
export {
  CUSTOMER_REGISTRY_FILTERS,
  CUSTOMER_WORKSPACE_SECTIONS,
  customerHref,
  customerRegistryFilterLabel,
  customerWorkspaceSectionLabel,
  filterCustomerRegistry,
  jobsForCustomer,
  matchesCustomerSearch,
  projectCustomerRegistry,
  projectCustomerRegistryItem,
  projectCustomerWorkspace,
  quotesForCustomer,
  requestsForCustomer,
  type CustomerRegistryFilter,
  type CustomerRegistryItem,
  type CustomerRegistryProjection,
  type CustomerWorkspaceActivity,
  type CustomerWorkspaceNextAction,
  type CustomerWorkspaceProjection,
  type CustomerWorkspaceSection,
} from "./workspace.js";
